services:
  application:
    image: gym-application
    build:
      context: .
      dockerfile: GymApplication.api/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    
