services:
  application:
    image: gym-application
    build:
      context: .
      dockerfile: GymApplication.api/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - postgres
    networks:
      - backend
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vk2p_gym
      POSTGRES_DB: gym
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=myPassword
  redis-insight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "5540:5540"
    environment:
      - REDISINSIGHT_REDIS_URI=redis://myPassword@redis:6379
    depends_on:
      - redis
volumes:
  postgres-data:
networks:
  backend:
    
